name: Do something

on:
  workflow_dispatch:
    inputs:
      foo:
        type: string
        required: false
      bar:
        type: string
        required: false

jobs:
  show-context:
    runs-on: ubuntu-latest
    steps:
      - name: Show github context object
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
